- alias: Mark resident as just arrived
  trigger:
    - platform: state
      entity_id: binary_sensor.marcin_home
      from: 'off'
      to: 'on'
    - platform: state
      entity_id: binary_sensor.natalia_home
      from: 'off'
      to: 'on'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.marcin_home' %}
            input_select.marcin_status_dropdown
          {% else %}
            input_select.natalia_status_dropdown
          {% endif %}
        option: Just Arrived
 
- alias: Mark resident as home
  trigger:
    - platform: state
      entity_id: input_select.marcin_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.natalia_status_dropdown
      to: 'Just Arrived'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.marcin_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
    - platform: state
      entity_id: input_select.natalia_status_dropdown
      from: 'Just Left'
      to: 'Just Arrived'
  condition:
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.marcin_status_dropdown' %}
            input_select.marcin_status_dropdown
          {% else %}
            input_select.natalia_status_dropdown
          {% endif %}
        option: Home
 
- alias: Mark resident as just left
  trigger:
    - platform: state
      entity_id: binary_sensor.marcin_home
      from: 'on'
      to: 'off'
    - platform: state
      entity_id: binary_sensor.natalia_home
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'binary_sensor.marcin_home' %}
            input_select.marcin_status_dropdown
          {% else %}
            input_select.natalia_status_dropdown
          {% endif %}
        option: Just Left
 
- alias: Mark resident as away
  trigger:
    - platform: state
      entity_id: input_select.marcin_status_dropdown
      to: 'Just Left'
      for:
        minutes: 5
    - platform: state
      entity_id: input_select.natalia_status_dropdown
      to: 'Just Left'
      for:
        minutes: 5
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.marcin_status_dropdown' %}
            input_select.marcin_status_dropdown
          {% else %}
            input_select.natalia_status_dropdown
          {% endif %}
        option: Away
        
- alias: Mark resident as extended away
  trigger:
    - platform: state
      entity_id: input_select.marcin_status_dropdown
      to: 'Away'
      for:
        hours: 24
    - platform: state
      entity_id: input_select.natalia_status_dropdown
      to: 'Away'
      for:
        hours: 24
  action:
    - service: input_select.select_option
      data_template:
        entity_id: >
          {% if trigger.entity_id == 'input_select.marcin_status_dropdown' %}
            input_select.marcin_status_dropdown
          {% else %}
            input_select.natalia_status_dropdown
          {% endif %}
        option: Extended Away