homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret latitude
  longitude: !secret longtitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret elevation
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Warsaw
  customize: !include ./configuration/customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret http_password
  ssl_certificate: !secret ssl_certificate_path
  ssl_key: !secret ssl_key_path
  base_url: !secret https_url
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123
  login_attempts_threshold: 5
  #base_url: !secret IP

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore: 
    - harmony

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - automation
      - binary_sensor
      - fan
      - input_boolean
      - input_number
      - light
      - sensor
      - switch
      
recorder:
  purge_interval: 2
  purge_keep_days: 2
  db_url: !secret dbcon
  
# View all events in a logbook
logbook:

logger:
  default: warning
  logs:
    homeassistant.components.automation: warning
    homeassistant.components.script: error
    homeassistant.components.xiaomi: error
    homeassistant.components.sensor.xiaomi: error
    homeassistant.components.switch.xiaomi: error
    homeassistant.components.binary_sensor: warning
    
# Track the sun
sun:

# Weather prediction
  # - platfom: template
    # sensors:
      # harmony_hub:
        # value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
        # friendly_name: 'Current Activity'
# Text to speech
tts:
  - platform: google


# input_boolean:
   # harmony_hub_headphones:
      # name: Listen to Music via Headphones
      # initial: off

ffmpeg:
  ffmpeg_bin: /data/data/com.termux/files/usr/bin/ffmpeg
 
alexa: !include ./configuration/alexa.yaml 
automation: !include_dir_merge_list automation
group: !include ./configuration/group.yaml
ifttt: !include ./configuration/ifttt.yaml
light: !include ./configuration/light.yaml
scene: !include ./configuration/scenes.yaml
remote: !include ./configuration/remote.yaml
xiaomi_aqara: !include ./configuration/xiaomi_aqara.yaml
device_tracker: !include ./configuration/device_tracker.yaml
media_player: !include ./configuration/media_player.yaml
input_select: !include ./configuration/input_select.yaml
input_boolean: !include ./configuration/input_boolean.yaml
input_number: !include ./configuration/input_number.yaml
sensor: !include_dir_merge_list sensors/sensor
binary_sensor: !include_dir_merge_list sensors/binary
#emulated_hue: !include ./configuration/emulated_hue.yaml
shell_command: !include ./configuration/shell_command.yaml
switch: !include ./configuration/switch.yaml
script: !include_dir_merge_list scripts
notify: !include ./configuration/notify.yaml
telegram_bot: !include ./configuration/telegram.yaml
alert: !include ./configuration/alerts.yaml
mqtt: !include ./configuration/mqtt.yaml
zone: !include ./configuration/zones.yaml
google_assistant: !include ./configuration/google_assistant.yaml
camera: !include ./configuration/camera.yaml
