- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      
- platform: template
  sensors:
    living_room_tv_source:
      value_template: '{{ states.media_player.living_room_tv.attributes["source"] }}'
      friendly_name: 'Living Room TV Source'