- id: motion_detected_bedroom_light
  alias: Turn on light in Bedroom when motion detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0000f954cf
      from: 'off'
      to: 'on'
    # - platform: state
      # entity_id: binary_sensor.marcin_kitchen
      # to: 'on'
    # - platform: state
      # entity_id: binary_sensor.natalia_kitchen
      # to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
    - condition: state
      entity_id: sensor.residents_status
      state: 'Home'
  action:
    - service: light.turn_on
      entity_id: light.bedroom

- id: presence_not_detected_bedroom_light
  alias: Turn off light in Bedroom when presence not detected
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0000f954cf
      to: 'off'
      for:
        seconds: 120  
    - platform: template
      value_template: "{% if is_state('binary_sensor.marcin_living_room', 'on') and is_state('binary_sensor.natalia_living_room', 'on') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state('binary_sensor.marcin_kitchen', 'on') and is_state('binary_sensor.natalia_kitchen', 'on') %}true{% endif %}"
    - platform: template
      value_template: "{% if is_state('binary_sensor.marcin_living_room', 'on') and is_state('binary_sensor.natalia_kitchen', 'on') %}true{% endif %}" 
    - platform: template
      value_template: "{% if is_state('binary_sensor.marcin_kitchen', 'on') and is_state('binary_sensor.natalia_living_room', 'on') %}true{% endif %}"
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.marcin_bedroom
        state: 'off'
      - condition: state
        entity_id: binary_sensor.natalia_bedroom
        state: 'off'
      - condition: state 
        entity_id: binary_sensor.motion_sensor_158d0000f954cf
        state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.bedroom

- alias: xiaomi bedroom brighten on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0000fd2037
        click_type: long_click_press
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_dim
      state: 'off'
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.brighten_light_bedroom
      
- alias: xiaomi bedroom brighten off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_158d0000fd2037
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_dim
      state: 'off'
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.bedroom_dim
      
- alias: xiaomi bedroom dim on
  initial_state: 'on'
  trigger:
    - platform: event
      event_type: click
      event_data:
        entity_id: binary_sensor.switch_158d0000fd2037
        click_type: long_click_press
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_dim
      state: 'on'
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: script.turn_on
      entity_id: script.dim_light_bedroom

- alias: xiaomi bedroom brighten off
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.switch_158d0000fd2037
      from: 'on'
      to: 'off'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.bedroom_dim
      state: 'on'
    - condition: state
      entity_id: light.bedroom
      state: 'on'
    - condition: state
      entity_id: input_boolean.sleep_mode
      state: 'off'
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.bedroom_dim