- alias: "PC LEDs Animation Speed"
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: input_number.pc_leds_animation_speed
  action:
    - service: mqtt.publish
      data_template:
        topic: "hass/pc_leds/set"
        payload: '{"transition":{{ trigger.to_state.state | int }}}'