- platform: ubus
  host: !secret rooter_host
  username: !secret rooter_user
  password: !secret rooter_password
  interval_seconds: 10
  consider_home: 21
  
- platform: owntracks
  max_gps_accuracy: 300