- platform: kodi
  host: !secret kodi_host
  name: !secret kodi_name
  
- platform: webostv
  host: !secret webostv_host
  mac: !secret webostv_mac
  name: Living Room TV
  timeout: 5
  filename: webostv.conf
  customize:
    sources:
      - livetv
      - youtube
      - makotv
      - netflix
      - hdmi2
      - plex
      
- platform: spotify
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret
  # aliases:
      # abc123def456: 'Living Room'
      # 9183abas000: 'Bed Room'