- platform: yr
  name: Weather
  monitored_conditions:
    - symbol
    - temperature
    - precipitation
    - windSpeed
    - pressure
    - humidity 
    
- platform: template
  sensors:
    current_activity:
      friendly_name: 'Current Activity'
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'